In [4]:
import sqlite3

import pandas as pd

#数据库连接
sql = sqlite3.connect(r'C:\Users\86132\Desktop\numpy库\test.db')
#连接数据库
df = pd.read_sql('select * from order_items', con =  sql)

display(df)

display(df[df['price']>=3999])

      id  order_id  product_id  quantity   price
0      1         1           1         1  6999.0
1      2         1           3         2  1999.0
2      3         2           6         3    89.0
3      4         2           8         1   399.0
4      5         2           9         2   199.0
..   ...       ...         ...       ...     ...
562  563       207           7         5   299.0
563  564       208           4         2  3999.0
564  565       208           7         4   299.0
565  566       208          30         4    59.0
566  567       208          26         1    89.0

[567 rows x 5 columns]

      id  order_id  product_id  quantity   price
0      1         1           1         1  6999.0
8      9         4           2         1  8999.0
21    22         8           4         1  3999.0
40    41        14           5         5  5999.0
47    48        17           2         4  8999.0
..   ...       ...         ...       ...     ...
525  526       192           1         4  6999.0
534  535       196           5         4  5999.0
536  537       196           2         5  8999.0
559  560       206           5         1  5999.0
563  564       208           4         2  3999.0

[72 rows x 5 columns]