In [3]:
"""
    pandas 中 的 merge 和 concat 类似，但主要是用于两组有 key column 的数据，统一索引的数据。通常也被用在 Database 的处理当中。
    合并时有 4 种方式 how = ['left', 'right', 'outer', 'inner']，默认值 how='inner'。

    默认情况下，merge() 会根据 共同的列（key） 来进行合并。如果不指定具体的列名，它会默认根据列名相同的列进行合并。
"""

import pandas as pd
left=pd.DataFrame({'key':['k0','k1','k2','k3'],
'A':['A0','A1','A2','A3'],
'B':['B0','B1','B2','B3'], })
right=pd.DataFrame({'key':['k0','k1','k4','k3'],
'C':['C0','C1','C2','C3'],
'D':['D0','D1','D2','D3'], })

print(left)
print(right)

  key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3
  key   C   D
0  k0  C0  D0
1  k1  C1  D1
2  k4  C2  D2
3  k3  C3  D3

In [ ]:
"""
      key   A   B
    0  k0  A0  B0
    1  k1  A1  B1
    2  k2  A2  B2
    3  k3  A3  B3
      key   C   D
    0  k0  C0  D0
    1  k1  C1  D1
    2  k4  C2  D2
    3  k3  C3  D3


    key   A   B     C    D
    0  k0  A0  B0   C0   D0
    1  k1  A1  B1   C1   D1
    2  k2  A2  B2   nan  nan
    3  k3  A3  B3   C3   D3
    4  k4  nan nan  C2  D2   如果是内连接，会丢掉有nan值的行

"""

In [5]:
print(pd.merge(left,right))

  key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k3  A3  B3  C3  D3

In [6]:
print(pd.merge(left,right,how='outer'))

  key    A    B    C    D
0  k0   A0   B0   C0   D0
1  k1   A1   B1   C1   D1
2  k2   A2   B2  NaN  NaN
3  k3   A3   B3   C3   D3
4  k4  NaN  NaN   C2   D2

In [7]:
# merge 的使用，参数 how=’left’进行合并
#左连接会保留左侧 DataFrame 的所有行，并将右侧 DataFrame 中匹配的行合并到左侧。
# 如果右侧没有匹配的行，左侧的数据仍然会出现在结果中，但右侧的列会填充为 NaN
left=pd.DataFrame({'key':['k0','k1','k2','k3'],
'A':['A0','A1','A2','A3'],
'B':['B0','B1','B2','B3'], })
right=pd.DataFrame({'key':['k0','k1','k4','k3'],
'C':['C0','C1','C2','C3'],
'D':['D0','D1','D2','D3'], })
pd.merge(left,right,how='left')

  key   A   B    C    D
0  k0  A0  B0   C0   D0
1  k1  A1  B1   C1   D1
2  k2  A2  B2  NaN  NaN
3  k3  A3  B3   C3   D3

In [8]:
#右连接会保留右侧 DataFrame 的所有行，并将左侧 DataFrame 中匹配的行合并到右侧。
# 如果左侧没有匹配的行，右侧的数据仍然会出现在结果中，但左侧的列会填充为 NaN
pd.merge(left,right,how='right')

  key    A    B   C   D
0  k0   A0   B0  C0  D0
1  k1   A1   B1  C1  D1
2  k4  NaN  NaN  C2  D2
3  k3   A3   B3  C3  D3